const I={upload:'<svg viewBox="0 0 24 24"><path d="M12 16V4m0 0L7 9m5-5 5 5M5 15v5h14v-5"/></svg>',car:'<svg viewBox="0 0 24 24"><path d="M5 17h14M6 17v2m12-2v2M4 13l2-6h12l2 6v4H4z"/></svg>',file:'<svg viewBox="0 0 24 24"><path d="M6 2h8l4 4v16H6zM14 2v5h5"/></svg>',lock:'<svg viewBox="0 0 24 24"><rect x="5" y="10" width="14" height="10" rx="2"/><path d="M8 10V7a4 4 0 018 0v3"/></svg>',history:'<svg viewBox="0 0 24 24"><path d="M4 12a8 8 0 108-8 8 8 0 00-7 4M4 4v5h5"/></svg>',trash:'<svg viewBox="0 0 24 24"><path d="M4 7h16M9 7V4h6v3m3 0l-1 14H7L6 7"/></svg>'};
const icon=n=>`<span class="icon">${I[n]||I.file}</span>`;
const labels=['المستندات','الاستخراج','مراجعة البيانات','خيارات إضافية','المعاينة','التوقيع','PDF'];
const requiredDocs=[['buyerFront','هوية المشتري','الوجه الأمامي'],['buyerBack','هوية المشتري','الوجه الخلفي'],['sellerFront','هوية البائع','الوجه الأمامي'],['sellerBack','هوية البائع','الوجه الخلفي'],['vehicleReg','ملكية المركبة','شهادة التسجيل'],['insuranceDoc','شهادة التأمين','بطاقة أو وثيقة']];
const f=(value='',sourceDocument='',confidence=.99)=>({value,sourceDocument,confidence,verifiedByUser:false});
const seed=()=>({id:crypto.randomUUID?.()||Date.now().toString(),createdAt:new Date().toISOString(),step:0,status:'draft',seller:{nameAr:f('علي حسن محمد','sellerFront',.98),nameEn:f('ALI HASAN MOHAMED','sellerFront',.97),idType:f('CPR','sellerFront',.99),idNumber:f('850101123','sellerFront',.94),nationality:f('بحريني','sellerFront',.96),gender:f('ذكر','sellerFront',.96),address:f('المنامة، مملكة البحرين','sellerBack',.78)},buyer:{nameAr:f('فاطمة أحمد يوسف','buyerFront',.98),nameEn:f('FATIMA AHMED YOUSIF','buyerFront',.96),cpr:f('920202456','buyerFront',.91),nationality:f('بحرينية','buyerFront',.97),gender:f('أنثى','buyerFront',.98),phone:f('','',0),address:f('المحرق، مملكة البحرين','buyerBack',.74)},vehicle:{plateNumber:f('582914','vehicleReg',.99),plateType:f('خصوصي','vehicleReg',.97),make:f('Toyota','vehicleReg',.98),model:f('Camry','vehicleReg',.98),color:f('أبيض','vehicleReg',.96),year:f('2022','vehicleReg',.99),country:f('اليابان','vehicleReg',.94),chassis:f('JTNB11HK8N3012345','vehicleReg',.93),engine:f('A25A123456','vehicleReg',.86),cc:f('2500','vehicleReg',.96),cylinders:f('4','vehicleReg',.97),seats:f('5','vehicleReg',.98),fuel:f('بنزين','vehicleReg',.97),steering:f('يسار','vehicleReg',.98),weight:f('1570 kg','vehicleReg',.82)},insurance:{company:f('شركة البحرين الوطنية للتأمين','insuranceDoc',.96),policyNumber:f('BNI-2026-44821','insuranceDoc',.92),startDate:f('2026-01-15','insuranceDoc',.96),endDate:f('2027-01-14','insuranceDoc',.96)},sale:{enabled:false,price:'',payment:'cash',date:new Date().toISOString().slice(0,10),condition:'بحالة جيدة',notes:''},documents:{},accidentReport:{enabled:false,fileName:'',governmentUrl:'https://www.bahrain.bh/'},signatures:{seller:'',buyer:''},autoDeleteDays:30});
let tx=load()||seed(), view='new';
function load(){try{return JSON.parse(localStorage.getItem('naql-current'))}catch{return null}}
function save(){localStorage.setItem('naql-current',JSON.stringify({...tx,documents:Object.fromEntries(Object.entries(tx.documents).map(([k,v])=>[k,{...v,data:''}]))})); toast('تم الحفظ تلقائيًا')}
function shell(){document.querySelector('#app').innerHTML=`<div class="layout"><aside class="sidebar"><div class="brand">${icon('car')}<span><b>نَقْل</b><small>Vehicle Transfer Assistant</small></span></div><nav><button class="nav-item active" data-view="new">＋ معاملة جديدة</button><button class="nav-item" data-view="history">${icon('history')} المعاملات</button></nav><div class="secure-note">${icon('lock')}<span><b>مساحة خاصة ومشفرة</b><small>لا إرسال حكومي تلقائيًا</small></span></div></aside><main class="main"><header><button id="menu">☰</button><b class="mobile-logo">نَقْل</b><div><button id="language">EN</button><button>مركز المساعدة</button></div></header><div id="content"></div></main></div>`;document.querySelector('[data-view="new"]').onclick=()=>createNewTransaction();document.querySelector('[data-view="history"]').onclick=()=>{view='history';setActiveNavigation('history');document.querySelector('.sidebar').classList.remove('open');render()};document.querySelector('#menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');document.querySelector('#language').onclick=()=>{document.documentElement.dir=document.documentElement.dir==='rtl'?'ltr':'rtl';toast('تم تبديل اتجاه الواجهة / Interface direction changed')};render()}
function setActiveNavigation(name){document.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===name))}
function createNewTransaction(){
  if(tx.step>0||Object.keys(tx.documents).length){
    const history=JSON.parse(localStorage.getItem('naql-history')||'[]');
    if(!history.some(item=>item.id===tx.id))history.unshift(tx);
    localStorage.setItem('naql-history',JSON.stringify(history));
  }
  tx=seed();
  view='new';
  localStorage.setItem('naql-current',JSON.stringify(tx));
  setActiveNavigation('new');
  document.querySelector('.sidebar').classList.remove('open');
  render();
  toast('تم إنشاء معاملة جديدة');
}
function progress(){return `<div class="wizard">${labels.map((x,i)=>`<button class="${i===tx.step?'active':''} ${i<tx.step?'done':''}" data-goto="${i}" ${i>tx.step?'disabled':''}><span>${i<tx.step?'✓':i+1}</span><small>${x}</small></button>`).join('')}</div>`}
function page(inner){return `<section class="page"><div class="page-top"><div><span class="eyebrow">معاملة رقم ${tx.vehicle.plateNumber.value||'جديدة'}</span><h1>${labels[tx.step]}</h1></div><span class="autosave">● محفوظ تلقائيًا</span></div>${progress()}${inner}</section>`}
function render(){if(view==='history')return renderHistory();const screens=[documentsScreen,extractScreen,reviewScreen,optionsScreen,previewScreen,signatureScreen,pdfScreen];document.querySelector('#content').innerHTML=page(screens[tx.step]());bindCommon();(binders[tx.step]||(()=>{}))()}
function documentsScreen(){const count=Object.keys(tx.documents).filter(k=>tx.documents[k]?.name).length;return `<div class="privacy">${icon('lock')}<div><b>خصوصيتك أولويتنا</b><p>لن نعتمد أي بيانات حساسة دون مراجعتك. الملفات محمية وغير متاحة عبر روابط عامة.</p></div></div><div class="section-head"><div><h2>صوّر أو ارفع المستندات المطلوبة</h2><p>${count} من 6 مستندات مرفوعة</p></div><b>${Math.round(count/6*100)}%</b></div><div class="meter"><i style="width:${count/6*100}%"></i></div><div class="documents">${requiredDocs.map(([id,title,sub])=>docCard(id,title,sub)).join('')}</div><label class="extra-upload">＋ إضافة مرفق آخر<input type="file" hidden></label>${footer('بدء استخراج البيانات',count===6)}`}
function docCard(id,title,sub){const d=tx.documents[id];return `<article class="document ${d?'ready':''}"><div class="doc-icon">${icon('file')}</div><div><h3>${title}</h3><p>${sub}</p><small>${d?`✓ ${d.name} • جاهز للتحليل`:'JPG, PNG أو PDF • حتى 10 MB'}</small></div>${d?`<button class="replace" data-id="${id}">استبدال</button>`:''}<label class="capture"><input data-doc="${id}" type="file" accept="image/*,application/pdf" capture="environment" hidden>${d?'إعادة التصوير':'التقاط صورة أو رفع ملف'}</label></article>`}
function extractScreen(){return `<div class="processing-card"><div class="scanner">${icon('file')}<i></i></div><h2 id="processTitle">نحلل مستنداتك بأمان…</h2><p>اكتشاف النوع ← قص الحواف وتصحيح المنظور ← تحسين النص ← OCR ← فهم الحقول بالذكاء الاصطناعي</p><div class="process-list">${['التحقق من جودة الصور','قراءة هويات البائع والمشتري','استخراج بيانات المركبة والتأمين','مطابقة الحقول وتجهيز المراجعة'].map((x,i)=>`<div class="process" data-process="${i}"><span>${i+1}</span><b>${x}</b><small>بانتظار البدء</small></div>`).join('')}</div><button class="primary" id="startOcr">بدء التحليل الذكي</button></div>`}
const sections={buyer:['بيانات المشتري',{nameAr:'الاسم بالعربية',nameEn:'الاسم بالإنجليزية',cpr:'الرقم الشخصي CPR',nationality:'الجنسية',gender:'الجنس',phone:'رقم الهاتف',address:'العنوان'}],seller:['بيانات البائع',{nameAr:'الاسم بالعربية',nameEn:'الاسم بالإنجليزية',idType:'نوع الهوية',idNumber:'CPR / CR',nationality:'الجنسية',gender:'الجنس',address:'العنوان'}],vehicle:['بيانات المركبة',{plateNumber:'رقم المركبة',plateType:'نوع اللوحة',make:'الشركة المصنعة',model:'الطراز',color:'اللون',year:'سنة الصنع',country:'بلد الصنع',chassis:'رقم الهيكل',engine:'رقم المحرك',cc:'السعة CC',cylinders:'الأسطوانات',seats:'المقاعد',fuel:'الوقود',steering:'جهة المقود',weight:'الوزن'}],insurance:['بيانات التأمين',{company:'شركة التأمين',policyNumber:'رقم الوثيقة',startDate:'تاريخ البداية',endDate:'تاريخ النهاية'}]};
function reviewScreen(){return `<div class="review-alert">راجع الحقول المحددة باللون البرتقالي — دقة الاستخراج أقل من 85%.</div>${Object.entries(sections).map(([key,[title,fields]])=>`<details class="form-section" open><summary><h2>${title}</h2><span>${Object.keys(fields).length} حقول</span></summary><div class="field-grid">${Object.entries(fields).map(([name,label])=>field(key,name,label)).join('')}</div></details>`).join('')}${footer('اعتماد البيانات والمتابعة',true)}`}
function field(group,name,label){const x=tx[group][name]||f();const low=x.confidence<.85;return `<label class="field ${low?'low':''}"><span>${label} ${low?'<em>راجع الحقل</em>':''}</span><input data-group="${group}" data-field="${name}" value="${esc(x.value)}"><small>دقة ${Math.round(x.confidence*100)}% • ${x.sourceDocument||'إدخال يدوي'}</small></label>`}
function optionsScreen(){return `<div class="option-grid"><article class="option"><div class="option-title"><div>${icon('file')}<span><h2>إنشاء عقد بيع</h2><p>عقد ثنائي اللغة عربي / إنجليزي</p></span></div><label class="switch"><input id="saleEnabled" type="checkbox" ${tx.sale.enabled?'checked':''}><i></i></label></div><div class="option-body ${tx.sale.enabled?'':'hidden'}" id="saleFields"><label>قيمة البيع (د.ب)<input id="price" type="number" value="${tx.sale.price}" placeholder="0.000"></label><label>طريقة الدفع<select id="payment"><option value="cash">نقدًا</option><option value="bank">تحويل بنكي</option><option value="other">أخرى</option></select></label><label>تاريخ البيع<input id="saleDate" type="date" value="${tx.sale.date}"></label><label>حالة المركبة<input id="condition" value="${tx.sale.condition}"></label><label class="wide">ملاحظات<textarea id="notes">${tx.sale.notes}</textarea></label></div></article><article class="option"><div class="option-title"><div>${icon('car')}<span><h2>تقرير حوادث المركبة</h2><p>الاستعلام عبر بوابة الحكومة الرسمية</p></span></div><label class="switch"><input id="accidentEnabled" type="checkbox" ${tx.accidentReport.enabled?'checked':''}><i></i></label></div><div class="option-body ${tx.accidentReport.enabled?'':'hidden'}" id="accidentFields"><div class="gov-note"><b>رقم المركبة: ${tx.vehicle.plateNumber.value}</b><p>لن نتجاوز تسجيل الدخول أو CAPTCHA. أكمل الطلب بنفسك في الموقع الرسمي ثم ارفع التقرير.</p><a href="${tx.accidentReport.governmentUrl}" target="_blank" rel="noopener">فتح بوابة حكومة البحرين ↗</a></div><label class="wide upload-report">رفع التقرير بعد تنزيله<input id="accidentFile" type="file" accept="application/pdf,image/*"><small>${tx.accidentReport.fileName||'PDF أو صورة'}</small></label></div></article><article class="option retention"><div><h2>الحذف التلقائي للصور الأصلية</h2><p>يمكن حذف صور الهويات نهائيًا بعد مدة محددة.</p></div><select id="retention"><option value="30">بعد 30 يومًا</option><option value="7">بعد 7 أيام</option><option value="0">لا تحذف تلقائيًا</option></select></article></div>${footer('المتابعة إلى المعاينة',true)}`}
function previewScreen(){return `<div class="preview-toolbar"><b>معاينة مستندات المعاملة</b><span>يُرجى التحقق قبل التوقيع</span></div><div class="paper"><div class="paper-head"><b>مملكة البحرين</b><span>الإدارة العامة للمرور</span><h2>استمارة تحويل ملكية مركبة</h2><em>TRANSFER OF OWNERSHIP ✓</em></div><div class="paper-grid"><section><h3>بيانات المشتري / BUYER'S DETAILS</h3><p>${tx.buyer.nameAr.value}</p><p>${tx.buyer.cpr.value} • ${tx.buyer.nationality.value}</p></section><section><h3>بيانات المالك / VEHICLE OWNER'S DETAILS</h3><p>${tx.seller.nameAr.value}</p><p>${tx.seller.idNumber.value} • ${tx.seller.nationality.value}</p></section><section class="wide"><h3>بيانات المركبة / VEHICLE DETAILS</h3><p>${tx.vehicle.make.value} ${tx.vehicle.model.value} — ${tx.vehicle.year.value} — ${tx.vehicle.color.value}</p><p>Plate: ${tx.vehicle.plateNumber.value} • Chassis: ${tx.vehicle.chassis.value}</p></section><section class="wide"><h3>بيانات التأمين / INSURANCE DETAILS</h3><p>${tx.insurance.company.value} • ${tx.insurance.policyNumber.value}</p></section></div><small class="template-note">محاكاة معاينة: في الربط الإنتاجي يُكتب النص فوق قالب PDF الرسمي دون تعديل خلفيته.</small></div>${tx.sale.enabled?saleContract():''}${footer('اعتماد المعاينة والمتابعة',true)}`}
function saleContract(){return `<div class="paper contract"><div class="paper-head"><h2>عقد بيع مركبة<br><small>VEHICLE SALE AGREEMENT</small></h2></div><p>أقر البائع <b>${tx.seller.nameAr.value}</b> ببيع المركبة رقم <b>${tx.vehicle.plateNumber.value}</b>، رقم الهيكل <b>${tx.vehicle.chassis.value}</b>، إلى المشتري <b>${tx.buyer.nameAr.value}</b> بقيمة <b>${tx.sale.price||'—'} د.ب</b>.</p><p>يقر البائع باستلام المبلغ، ويقر المشتري باستلام المركبة بحالتها الموضحة. يتحمل البائع المخالفات السابقة لتاريخ ${tx.sale.date} والمشتري ما بعده.</p><div class="contract-sign"><span>توقيع البائع</span><span>توقيع المشتري</span></div></div>`}
function signatureScreen(){return `<div class="signature-intro"><h2>وقّع بالإصبع أو اترك الخانات فارغة</h2><p>لن يُضاف أي توقيع دون موافقتك الصريحة.</p><label><input type="checkbox" id="blankSign"> سأطبع الملف وأوقّعه يدويًا</label></div><div class="signature-grid"><div><h3>توقيع البائع</h3><canvas id="sellerCanvas"></canvas><button data-clear="seller">مسح التوقيع</button></div><div><h3>توقيع المشتري</h3><canvas id="buyerCanvas"></canvas><button data-clear="buyer">مسح التوقيع</button></div></div><label class="consent"><input type="checkbox" id="consent"> أوافق على إدراج التوقيعات المرسومة في المستند النهائي.</label>${footer('تأكيد وإنشاء ملف PDF',true)}`}
function pdfScreen(){const filename=`Vehicle-Transfer_${tx.vehicle.plateNumber.value}_${new Date().toISOString().slice(0,10)}.pdf`;return `<div class="success"><span>✓</span><h2>ملف المعاملة جاهز</h2><p>تم ترتيب الغلاف، الاستمارة، العقد، تقرير الحوادث، الهويات، ملكية المركبة والتأمين.</p><div class="file-ready">${icon('file')}<div><b>${filename}</b><small>ملف PDF آمن • جاهز للطباعة</small></div></div><button class="primary" id="downloadPdf">تنزيل / طباعة PDF</button><button class="secondary" id="newTx">بدء معاملة جديدة</button><div class="disclaimer"><b>تنبيه مهم</b><p>هذا الملف أُعد للمساعدة فقط. التطبيق ليس بديلًا عن الخدمات الرسمية ولا يرسل المعاملة إلى أي جهة حكومية.</p></div></div>`}
function footer(text,enabled){return `<div class="actions"><button class="secondary" id="back" ${tx.step===0?'disabled':''}>السابق</button><button class="primary" id="next" ${enabled?'':'disabled'}>${text} ←</button></div>`}
function bindCommon(){document.querySelectorAll('[data-goto]').forEach(b=>b.onclick=()=>{tx.step=+b.dataset.goto;render()});const back=document.querySelector('#back'),next=document.querySelector('#next');if(back)back.onclick=()=>{tx.step=Math.max(0,tx.step-1);render()};if(next)next.onclick=()=>{if(tx.step===2){Object.values(tx).filter(v=>v&&typeof v==='object').forEach(g=>Object.values(g).forEach?.(x=>{if(x?.value!==undefined)x.verifiedByUser=true}))}tx.step=Math.min(6,tx.step+1);tx.status=tx.step===6?'completed':'draft';save();render()}}
const binders=[()=>{document.querySelectorAll('[data-doc]').forEach(input=>input.onchange=e=>{const file=e.target.files[0];if(!file)return;if(file.size>10*1024*1024)return toast('حجم الملف أكبر من 10 MB');tx.documents[input.dataset.doc]={name:file.name,type:file.type,size:file.size,data:URL.createObjectURL(file)};save();render()});document.querySelector('.extra-upload input').onchange=e=>{if(e.target.files[0])toast('تمت إضافة المرفق الإضافي')}},()=>{document.querySelector('#startOcr').onclick=()=>{const rows=[...document.querySelectorAll('.process')];document.querySelector('#startOcr').disabled=true;rows.forEach((row,i)=>setTimeout(()=>{row.classList.add('complete');row.querySelector('span').textContent='✓';row.querySelector('small').textContent='اكتمل بنجاح';if(i===rows.length-1)setTimeout(()=>{tx.step=2;save();render()},600)},700*(i+1))) }},()=>{document.querySelectorAll('.field input').forEach(input=>input.oninput=()=>{const x=tx[input.dataset.group][input.dataset.field];x.value=input.value;x.verifiedByUser=true;x.confidence=1;input.closest('.field').classList.remove('low')})},()=>{const sale=document.querySelector('#saleEnabled'),acc=document.querySelector('#accidentEnabled');sale.onchange=()=>{tx.sale.enabled=sale.checked;document.querySelector('#saleFields').classList.toggle('hidden',!sale.checked)};acc.onchange=()=>{tx.accidentReport.enabled=acc.checked;document.querySelector('#accidentFields').classList.toggle('hidden',!acc.checked)};['price','payment','saleDate','condition','notes'].forEach(id=>{const el=document.querySelector('#'+id);if(el)el.onchange=()=>tx.sale[id==='saleDate'?'date':id]=el.value});document.querySelector('#retention').value=tx.autoDeleteDays;document.querySelector('#retention').onchange=e=>tx.autoDeleteDays=+e.target.value;document.querySelector('#accidentFile')?.addEventListener('change',e=>{tx.accidentReport.fileName=e.target.files[0]?.name||'';toast('تم إرفاق تقرير الحوادث')})},()=>{},()=>{setupCanvas('seller');setupCanvas('buyer');document.querySelectorAll('[data-clear]').forEach(b=>b.onclick=()=>{const c=document.querySelector(`#${b.dataset.clear}Canvas`);c.getContext('2d').clearRect(0,0,c.width,c.height);tx.signatures[b.dataset.clear]=''});document.querySelector('#consent').onchange=e=>{if(e.target.checked){['seller','buyer'].forEach(k=>{const c=document.querySelector(`#${k}Canvas`);tx.signatures[k]=c.toDataURL()})}}},()=>{document.querySelector('#downloadPdf').onclick=()=>window.print();document.querySelector('#newTx').onclick=()=>{localStorage.removeItem('naql-current');tx=seed();render()}}];
function setupCanvas(who){const c=document.querySelector(`#${who}Canvas`),ctx=c.getContext('2d');c.width=c.clientWidth*devicePixelRatio;c.height=170*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio);ctx.lineWidth=2.2;ctx.lineCap='round';ctx.strokeStyle='#102b46';let drawing=false;const pos=e=>{const r=c.getBoundingClientRect(),p=e.touches?.[0]||e;return [p.clientX-r.left,p.clientY-r.top]};c.onpointerdown=e=>{drawing=true;ctx.beginPath();ctx.moveTo(...pos(e));c.setPointerCapture(e.pointerId)};c.onpointermove=e=>{if(!drawing)return;ctx.lineTo(...pos(e));ctx.stroke()};c.onpointerup=()=>drawing=false}
function renderHistory(){let stored=[];try{stored=JSON.parse(localStorage.getItem('naql-history')||'[]')}catch{};const samples=[tx,...stored.filter(item=>item.id!==tx.id)];document.querySelector('#content').innerHTML=`<section class="page"><div class="page-top"><div><span class="eyebrow">لوحة المتابعة</span><h1>المعاملات السابقة</h1></div><button class="primary" id="fresh">＋ معاملة جديدة</button></div><div class="history-list">${samples.map((t,i)=>`<article><b class="plate">${t.vehicle.plateNumber.value||'مسودة'}</b><div><h3>${t.buyer.nameAr.value||'مشتري غير محدد'} ← ${t.seller.nameAr.value||'بائع غير محدد'}</h3><p>${new Date(t.createdAt).toLocaleDateString('ar-BH')} • ${t.status==='completed'?'مكتملة':'مسودة'}</p></div><span class="badge ${t.status}">${t.status==='completed'?'مكتملة':'مسودة'}</span><button data-open="${i}">فتح</button><button class="danger" data-delete="${i}">${icon('trash')}</button></article>`).join('')}</div></section>`;document.querySelector('#fresh').onclick=createNewTransaction;document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{tx=samples[+b.dataset.open];view='new';localStorage.setItem('naql-current',JSON.stringify(tx));setActiveNavigation('new');render()});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('حذف المعاملة وجميع بياناتها نهائيًا؟')){const removed=samples.splice(+b.dataset.delete,1)[0];localStorage.setItem('naql-history',JSON.stringify(samples.filter(item=>item.id!==tx.id)));if(removed.id===tx.id){tx=seed();localStorage.setItem('naql-current',JSON.stringify(tx))}renderHistory()}})}
function esc(x){return String(x??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
shell();
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
